#!/bin/sh
#
#  Copyright 2020 ModMyClassic (https://modmyclassic.com/license)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
echo "           ohhhhy: hhhhhs\` ohhhhy.  ohhy ohhhhh\`-yhhhy:hhhhhs  .syyyyyyyyyyyyyyyyyyyyyyyyys\`          "
echo "           yMN-hMN MMy:MMo:MM+-NMy  .hMm yMM::- dMm--.\`-yMM-.  hMdoyysymsmdoNMN+sMMdoysoNMm           "
echo "           yMMdNNs MMNmMM::MM: NMh   hMm yMMdd. dMd     yMM   -MMhsMMdoMh::mMN/my+N:mMMoyM+           "
echo "           yMN\`\`   MMs\`MMs-MMy+NMs:++mMd yMM+++\`hMm+++  yMM   hMMmshhyhmyMNyNssyyshmsysyMm\`           "
echo "           :o+     oo: oo: -+oo+/\`:ooo/\` :ooooo\`\`/ooo+  :o+   /oooooooooooooooooooooooooo-            "
echo "  .::::::::::::::::::::::::-   \`::::::::::::::---..\`\`          -:::::::\`        \`\`..--::::::::::::::\` "
echo "  oMMMMMMMMMMMMMMMMMMMMMMMMh   :MMMMMMMMMMMMMMMMMMMNmhs:\`      hMMMMMMM/     \`/shmNMMMMMMMMMMMMMMMMN\` "
echo "  oMMMMMMMMMMMMMMMMMMMMMMMM:   :MMMMMMMMMMMMMMMMMMMMMMMMd/     hMMMMMMM/   \`omMMMMMMMMMMMMMMMMMMMMMy  "
echo "  oMMMMMMMNmmmmmmmmmmmmmmmd    :MMMMMMMNddddddddmNMMMMMMMM/    hMMMMMMM/   sMMMMMMMMmdhhhhhhhhhhhhh-  "
echo "  oMMMMMMMy\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`     :MMMMMMMy        \`.sMMMMMMMm    hMMMMMMM/  \`MMMMMMMM/\`                 "
echo "  oMMMMMMMy                    :MMMMMMMy           MMMMMMMM    hMMMMMMM/  .MMMMMMMM\`                  "
echo "  oMMMMMMMh...............\`    :MMMMMMMy          \`MMMMMMMM    hMMMMMMM/  \`NMMMMMMMd+:--.\`\`           "
echo "  oMMMMMMMNmmmmmmmmmmmmmmm-    :MMMMMMMy       \`\`-yMMMMMMMh    hMMMMMMM/   sMMMMMMMMMMMNNmmdhyo/-\`    "
echo "  oMMMMMMMMMMMMMMMMMMMMMMm     :MMMMMMMNddddddmmmNMMMMMMMm.    hMMMMMMM/    +dMMMMMMMMMMMMMMMMMMMmy:  "
echo "  oMMMMMMMMMMMMMMMMMMMMMM+     :MMMMMMMMMMMMMMMMMMMMMMMdo\`     hMMMMMMM/     \`-+shdmNNMMMMMMMMMMMMMNo "
echo "  oMMMMMMMh..............\`     :MMMMMMMMNNNNNMMMMMMMMo-\`       hMMMMMMM/          \`\`...:/+oyNMMMMMMMM."
echo "  oMMMMMMMy                    :MMMMMMMh...../NMMMMMMm-        hMMMMMMM/                    .MMMMMMMM:"
echo "  oMMMMMMMy                    :MMMMMMMy      :NMMMMMMN+       hMMMMMMM/                    \`MMMMMMMM:"
echo "  oMMMMMMMdooooooooooooooooo\`  :MMMMMMMy       .dMMMMMMMy\`     hMMMMMMM/    //////////////+smMMMMMMMN\`"
echo "  oMMMMMMMMMMMMMMMMMMMMMMMMm   :MMMMMMMy        \`hMMMMMMMd.    hMMMMMMM/   :MMMMMMMMMMMMMMMMMMMMMMMN/\`"
echo "  oMMMMMMMMMMMMMMMMMMMMMMMMm   :MMMMMMMy        \`hMMMMMMMd.    hMMMMMMM/   :MMMMMMMMMMMMMMMMMMMMMMMN/ "
echo "  oMMMMMMMMMMMMMMMMMMMMMMMMo   :MMMMMMMy          sMMMMMMMN:   hMMMMMMM/   hMMMMMMMMMMMMMMMMMMMMMmo.  "
echo "  :yyyyyyyyyyyyyyyyyyyyyyyy\`   .yyyyyyy+           /yyyyyyyy-  +yyyyyyy:  \`yyyyyyhhhhhhhyyysso/-\`     "
echo
echo "--------------------------------------------------------------------------------------------------------"
echo "  ModMyClassic.com / https://discordapp.com/invite/8gygsrw                                              "
echo "--------------------------------------------------------------------------------------------------------"